### ISSUE TITLE
Obsolete API/header found in document

### ISSUE THREAD

**Issue by kenny-y** [ros2/rcl#123]
in `publisher.h', the embedded API document describes below usage, which is obsolete:

```
#include <rosidl_generator_c/message_type_support.h>
rosidl_message_type_support_t * string_ts =
  ROSIDL_GET_MESSAGE_TYPE_SUPPORT(std_msgs, String);
```

The correction might be:

```
#include <rosidl_generator_c/message_type_support_struct.h>
const rosidl_message_type_support_t * ts =
  ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, String);
```

Some of them occur multiple times, e.g. the obsolete header is x3.

**Comment by wjwwood** [comment]
Based on this: https://github.com/ros2/rosidl/blob/ef23dbf8e07af2381757829cacf9be97173acba6/rosidl_generator_c/include/rosidl_generator_c/message_type_support_struct.h#L26

That sounds right. Can you open a pull request to fix this? I'd like to get you some attribution for the fixup 😄. Otherwise I'll pick it up later.
