### ISSUE TITLE
Why #include "./header_in_source_dir.h" ?

### ISSUE THREAD

**Issue by astralien3000** [ros2/rcl#304]
What is the rationale to use includes like this : 
```c
#include "header_in_include_path.h"
#include "./header_in_source_dir.h"
```
Instead of the "more classic" : 
```c
#include <header_in_include_path.h>
#include "header_in_source_dir.h"
```

I'm asking that because the Arduino build system seems to be allergic to the `#include "./header_in_source_dir.h"` form.

Thanks !

**Comment by clalancette** [comment]
Presumably it is to make sure that you get the header file you expect, particularly with very common header file names like "common.h".  But I didn't write that code, so I'm not sure; maybe @wjwwood has some insight.  In any case, I'm not a huge fan of the `#include "./header_in_source.h"` style anyway, and things seem to build without it, so I would be for switching to the more traditional/classic use, along with maybe renaming some of the "headers-in-source-dir.h" files to be less generic.

**Comment by wjwwood** [comment]
> Presumably it is to make sure that you get the header file you expect, particularly with very common header file names like "common.h".

That's exactly it, things like `string.h` or `types.h`. And since they don't have namespace like `rcl/common.h` the `./common.h` helps. I tried to do it everywhere for convenience, and also it's a clue to people reading the code that it is an rcl header and not a system one despite not having a namespace.

I'm not opposed to changing it, but I'd prefer not to since not all machines will have `common.h`, so while it might work on one machine for now, it may break on another machine or in the future.

I'd rather understand why it's an issue (it's completely valid C code after all) and address that issue. The `"` versus `<` is pretty much meaningless and all compilers we use right now treats them identically.

**Comment by astralien3000** [comment]
As far as I have tested (on gcc), "common.h" has the same behavior as "./common.h" : if you remove common.h from src, it will search in the include paths. The same way, <common.h> and <./common.h> have the same behavior (try including <stdio.h> and <./stdio.h> for example).

And I don't agree at all with your last senstence, "" and <> are not treated identically, neither by [visual studio](https://msdn.microsoft.com/en-us/library/36k2cdd4.aspx), nor by [gcc](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html). And the difference between their treatment is quite what you are trying to express with "common.h" and "./common.h".

**Comment by astralien3000** [comment]
> I'd rather understand why it's an issue (it's completely valid C code after all) and address that issue.

👍  I will try to find out anyway. I suspect the answer is simply that Arduino has an awful build system 😞 .

**Comment by astralien3000** [comment]
After some tests, here is the commands that fails (Arduino under Windows) : 
```sh
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10807 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR "-DROS_PACKAGE_NAME=\"\"" "-ID:\Arduino\hardware\arduino\avr\cores\arduino" "-ID:\Arduino\hardware\arduino\avr\variants\mega" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rclc" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rcl" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rcl_interfaces" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rcl_interfaces__rosidl_generator_c" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rcutils" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rosidl_generator_c" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rosidl_typesupport_interface" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rmw_implementation" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rmw" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rmw_fake" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\std_msgs" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\std_msgs__rosidl_generator_c" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\rosidl_typesupport_introspection_c" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\builtin_interfaces" "-ID:\work\ros2_ino_ws\install\Arduino\libraries\builtin_interfaces__rosidl_generator_c" "D:\work\ros2_ino_ws\install\Arduino\libraries\rcl\client.c" -o nul
```

While the same commande works if I remove `-o nul` at the end.
And if I try the same command under linux, it works even with `-o nul`...
I also tested an ARM-based Arduino board, and there is no problem while keeping the `-o nul`.
Seems like it is a bug in some version of avr-gcc.

Ok, from my side you can close this issue once you have made a choice. I have stated my arguments and the question raised is not so important, especially if it means modifying all the packages, that's a lot of work I guess.

**Comment by clalancette** [comment]
@wjwwood and I had another short conversation about this, and we agreed that we should remove the "./header_in_source_dir.h" and move to just "header_in_source_dir.h".  It's fairly low priority for us, though; if you'd like to see it sooner, a PR would be appreicated @astralien3000 .  Thanks!

**Comment by clalancette** [comment]
I poked at this just a little while waiting for other stuff to compile.  Here's what I found:

The [Google style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) (which we mostly follow, with some exceptions), agrees and says that we should *not* use "./" for #include.  However, they also seem to assume that your directory structure is something like `src/foo/bar.h` so you can always do `#include "foo/bar.h"`, which is not the case in our codebase.

I attempted to remove most of the `#include ./header.h`, which compiles fine, but runs afoul of the cpplint checker (which presumably is trying to enforce the Google style).  Examples of how it fails is here: https://ci.ros2.org/job/ci_linux/5317/#showFailuresLink .  Given that, I'm not sure this change will be worth it; we'd either have to a) conform more closely to the Google directory structure, or b) disable cpplint for those includes (either with annotations in the source or an explicit "disable this warning").  Either case is a bunch of churn, for not much benefit.  I'm going to stop poking at this for now, since I'm not sure how to proceed.

**Comment by wjwwood** [comment]
In retrospect that might have been why I ended up with `./` because it's not something I usually do.

I probably didn't do the `src/foo/bar.h` because I didn't want to add `src` to the include path and for a single file in say `src/ping.c` you could then do `#include "foo/bar.h"`, but that imposed a structure on your `src` folder and it makes it hard to see (at the location of include) which headers are public and which are private.

I'm fine with leaving it as-is, but it does it leave @astralien3000 hanging?

**Comment by astralien3000** [comment]
Hello !

Sorry I could not work on this recently.
So if I understand well, `cpplint` force to use a sub directory ? That is weird.
I don't want to fight with cpplint, so I don't mind leaving it as-is.

**Comment by clalancette** [comment]
> I probably didn't do the `src/foo/bar.h` because I didn't want to add `src` to the include path and for a single file in say `src/ping.c` you could then do `#include "foo/bar.h"`, but that imposed a structure on your `src` folder and it makes it hard to see (at the location of include) which headers are public and which are private.

Yeah, that matches my thinking as well.

> So if I understand well, `cpplint` force to use a sub directory ? That is weird.
> I don't want to fight with cpplint, so I don't mind leaving it as-is.

That's what it seems like to me, though I didn't do any additional testing of cpplint to see what things it "would" accept.

In either case, since you seem to agree, I'm going to close this issue out.  Feel free to reopen if you come across new information or come up with a different way to accomplish this goal.  Thanks!
